### ISSUE TITLE
大佬可以留下联系方式吗

### ISSUE THREAD

**Issue by DavidMGT** [xushengjiang0/flutter_yuedu#3]
: {PermissionGroup.storage: PermissionStatus.granted}
E/flutter (21495): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method listen on channel plugins.megstar.com/update_version)
这个自动更新

**Comment by jason1024po** [comment]
额，才看到。你应该解决了吧。xusj10@163.com
